name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Install
        run: |
          sudo apt-get install cmake build-essential libboost-system-dev libboost-filesystem-dev libcrypto++-dev libgtkmm-3.0-dev g++-13 liblzma-dev
          wget http://ftp.gnome.org/pub/GNOME/sources/libxml++/3.0/libxml++-3.0.1.tar.xz -O /tmp/libxml++-3.0.1.tar.xz
          tar -xf /tmp/libxml++-3.0.1.tar.xz -C /tmp
          cd /tmp/libxml++-3.0.1
          ./configure --disable-shared --enable-static
          make
          sudo make install

      - name: Get cmake
        uses: lukka/get-cmake@latest

      - name: Set compiler
        run: |
          echo "CC=gcc-13" >> $GITHUB_ENV
          echo "CXX=g++-13" >> $GITHUB_ENV

      - name: Run cmake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ninja"
          buildPreset: "ninja"
